mysql:
  host: "localhost"
  port: 3306
  database: "minecraft_server"
  username: "minecraft"
  password: "Tobi1748"  # The password you set!

  pool:
    maximum-pool-size: 8
    minimum-idle: 2
    connection-timeout: 20000
    idle-timeout: 600000
    max-lifetime: 1800000

redis:
  host: "redis-13511.crce218.eu-central-1-1.ec2.cloud.redislabs.com"
  port: 13511
  password: "TUdVa4lhKdpQDIiI5ynKrb3ylzllqmmp"