# MySQL Database Configuration
# MySQL Database Configuration
mysql:
  # Railway MySQL connection (SAME as LuckPerms!)
  host: "yamabiko.proxy.rlwy.net"
  port: 35834
  database: "railway"
  username: "root"
  password: "hECALfMctdYillfDoVsaVDDismxZnMm"

  # Connection pool settings (HikariCP)
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

  # Connection properties for performance
  properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

# Redis Configuration (no change needed)
redis:
  host: "redis-13511.crce218.eu-central-1-1.ec2.cloud.redislabs.com"
  port: 13511
  password: "TUdVa4lhKdpQDIiI5ynKrb3ylzllqmmp"

  pool:
    max-total: 20
    max-idle: 10
    min-idle: 2

  key-prefix: "mcserver:"

  channels:
    server-heartbeat: "server:heartbeat"
    game-state: "game:state"
    player-queue: "player:queue"
    player-stats: "player:stats"
    server-command: "server:command"