name: LobbyPlugin
version: '1.0.0'
main: com.yourserver.lobby.LobbyPlugin
api-version: '1.21'
author: MCBZH
description: Lobby system with scoreboards, tab list, GUIs, and cosmetics

# Depends on CorePlugin for database and Redis
depend:
  - CorePlugin
  - APIModule

# Soft dependencies (optional)
softdepend:
  - NPCPlugin
  - LuckPerms
  - SocialPlugin


load: POSTWORLD
loadafter:
  - SocialPlugin


commands:
  lobby:
    description: Main lobby command
    usage: /<command> [reload|setspawn|item]
    permission: lobby.admin
    aliases: [hub, l]

  spawn:
    description: Teleport to spawn
    usage: /<command>
    permission: lobby.spawn
    aliases: [s]

  refreshnametags:
    description: Refresh all player nametags and tab names
    usage: /<command>
    permission: lobby.admin
    aliases: [ rnt, refreshnames ]

permissions:
  lobby.admin:
    description: Access to lobby admin commands
    default: op

  lobby.spawn:
    description: Teleport to spawn
    default: true

  lobby.cosmetics:
    description: Access to cosmetics
    default: true

  lobby.cosmetics.vip:
    description: Access to VIP cosmetics
    default: false